/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalresprog;

import javax.swing.JOptionPane;

/**
 *
 * @author arell
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        jDateChooser1.setEnabled(false);
        partySize.setEnabled(false);
        Time.setEnabled(false);
        reservationFor.setEnabled(false);
        status.setEnabled(false);
        confirmChanges.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userTab = new javax.swing.JTabbedPane();
        tab = new javax.swing.JPanel();
        Background = new javax.swing.JLabel();
        statusButt = new javax.swing.JButton();
        homeButt = new javax.swing.JButton();
        profileButt = new javax.swing.JButton();
        reservationButt = new javax.swing.JButton();
        tab2 = new javax.swing.JPanel();
        firstName = new javax.swing.JTextField();
        firstName1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        firstName2 = new javax.swing.JTextField();
        firstName3 = new javax.swing.JTextField();
        firstName4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();
        profileButt2 = new javax.swing.JButton();
        homeButt2 = new javax.swing.JButton();
        statusButt2 = new javax.swing.JButton();
        saveInfo = new javax.swing.JToggleButton();
        signOut = new javax.swing.JToggleButton();
        tab3 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        partySize = new javax.swing.JComboBox<>();
        Time = new javax.swing.JComboBox<>();
        reservationFor = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        confirmChanges = new javax.swing.JButton();
        cancelReservation = new javax.swing.JButton();
        Background2 = new javax.swing.JLabel();
        profileButt3 = new javax.swing.JButton();
        homeButt3 = new javax.swing.JButton();
        statusButt3 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        PWhole = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 675));
        getContentPane().setLayout(null);

        tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcImage/Homepage.png"))); // NOI18N
        tab.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        statusButt.setText("jButton1");
        statusButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButtActionPerformed(evt);
            }
        });
        tab.add(statusButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 190, 100));

        homeButt.setText("jButton1");
        tab.add(homeButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 150, 100));

        profileButt.setText("jButton1");
        profileButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtActionPerformed(evt);
            }
        });
        tab.add(profileButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, 100));

        reservationButt.setText("jButton1");
        reservationButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtActionPerformed(evt);
            }
        });
        tab.add(reservationButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 260, 80));

        userTab.addTab("tab1", tab);

        tab2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tab2.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 430, 30));
        tab2.add(firstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 400, 30));
        tab2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 280, 30));
        tab2.add(firstName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 430, 30));
        tab2.add(firstName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 430, 30));
        tab2.add(firstName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 430, 30));

        jLabel1.setText("USER ID:");
        tab2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 340, 30));

        Background1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcImage/Homepage (5).png"))); // NOI18N
        tab2.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        profileButt2.setText("jButton1");
        tab2.add(profileButt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 130, 100));

        homeButt2.setText("jButton1");
        homeButt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButt2ActionPerformed(evt);
            }
        });
        tab2.add(homeButt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 160, 100));

        statusButt2.setText("jButton1");
        statusButt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButt2ActionPerformed(evt);
            }
        });
        tab2.add(statusButt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 190, 100));

        saveInfo.setText("jToggleButton1");
        tab2.add(saveInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 150, 60));

        signOut.setText("jToggleButton1");
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });
        tab2.add(signOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 150, 60));

        userTab.addTab("tab2", tab2);

        tab3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tab3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 180, 40));

        partySize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(choose)", "1 guest", "2 guests", "3 guests", "4 guests", "5 guests", "6 guests", "7 guests", "8 guests", "9 guests", "10 guests", "11 guests", "12 guests", "13 guest", "14 guests", "15 guests", "16 guests", "17 guests", "18 guests", "19 guests", "20 guests", " " }));
        partySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partySizeActionPerformed(evt);
            }
        });
        tab3.add(partySize, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 160, 50));

        Time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(choose)", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM", "10:00 PM" }));
        Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeActionPerformed(evt);
            }
        });
        tab3.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 160, 50));

        reservationFor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab3.add(reservationFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 380, 40));
        tab3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 180, 30));

        confirmChanges.setBackground(new java.awt.Color(153, 0, 0));
        confirmChanges.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmChanges.setForeground(new java.awt.Color(255, 255, 255));
        confirmChanges.setText("Confirm Changes");
        confirmChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChangesActionPerformed(evt);
            }
        });
        tab3.add(confirmChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 160, 60));

        cancelReservation.setBackground(new java.awt.Color(153, 0, 0));
        cancelReservation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelReservation.setForeground(new java.awt.Color(255, 255, 255));
        cancelReservation.setText("Cancel Reservation");
        cancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationActionPerformed(evt);
            }
        });
        tab3.add(cancelReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 160, 160, 60));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcImage/Homepage (2).png"))); // NOI18N
        tab3.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        profileButt3.setText("jButton1");
        profileButt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButt3ActionPerformed(evt);
            }
        });
        tab3.add(profileButt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, 100));

        homeButt3.setText("jButton1");
        homeButt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButt3ActionPerformed(evt);
            }
        });
        tab3.add(homeButt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 150, 100));

        statusButt3.setText("jButton1");
        statusButt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButt3ActionPerformed(evt);
            }
        });
        tab3.add(statusButt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 190, 100));

        edit.setText("jButton1");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        tab3.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 150, 60));

        cancel.setText("jButton2");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        tab3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 130, 60));

        userTab.addTab("tab3", tab3);

        getContentPane().add(userTab);
        userTab.setBounds(0, -20, 1200, 690);

        PWhole.setPreferredSize(new java.awt.Dimension(1200, 675));
        PWhole.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PWhole);
        PWhole.setBounds(0, 0, 1200, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusButt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButt3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_statusButt3ActionPerformed

    private void homeButt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButt3ActionPerformed
        // TODO add your handling code here:
        userTab.setSelectedComponent(tab);
    }//GEN-LAST:event_homeButt3ActionPerformed

    private void profileButt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButt3ActionPerformed
        // TODO add your handling code here:
        userTab.setSelectedComponent(tab2);
    }//GEN-LAST:event_profileButt3ActionPerformed

    private void TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeActionPerformed

    private void partySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partySizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partySizeActionPerformed

    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            LOGIN loginFrame = new LOGIN(); // Create an instance of LOGIN frame
            loginFrame.setVisible(true); // Make the LOGIN frame visible
        }
    }//GEN-LAST:event_signOutActionPerformed

    private void statusButt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButt2ActionPerformed
        // TODO add your handling code here:
        userTab.setSelectedComponent(tab3);
    }//GEN-LAST:event_statusButt2ActionPerformed

    private void homeButt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButt2ActionPerformed
        // TODO add your handling code here:
        userTab.setSelectedComponent(tab);
    }//GEN-LAST:event_homeButt2ActionPerformed

    private void reservationButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButtActionPerformed
        // TODO add your handling code here:
        HomeFrame.this.dispose();
        ReservationFrame reservationFrame = new ReservationFrame(); // Create an instance of ReservationFrame
        reservationFrame.setVisible(true); // Make the ReservationFrame visible

    }//GEN-LAST:event_reservationButtActionPerformed

    private void profileButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtActionPerformed
        // TODO add your handling code here:
        userTab.setSelectedComponent(tab2);
    }//GEN-LAST:event_profileButtActionPerformed

    private void statusButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButtActionPerformed
        // TODO add your handling code here:
        userTab.setSelectedComponent(tab3);
    }//GEN-LAST:event_statusButtActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        jDateChooser1.setDate(null);
        partySize.setSelectedIndex(0);
        Time.setSelectedIndex(0);
        reservationFor.setText("");
        jDateChooser1.setEnabled(false);
        partySize.setEnabled(false);
        Time.setEnabled(false);
        reservationFor.setEnabled(false);
        confirmChanges.setEnabled(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        jDateChooser1.setEnabled(true);
        partySize.setEnabled(true);
        Time.setEnabled(true);
        reservationFor.setEnabled(true);
        confirmChanges.setEnabled(true);
    }//GEN-LAST:event_editActionPerformed

    private void confirmChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmChangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmChangesActionPerformed

    private void cancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelReservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Background2;
    private javax.swing.JPanel PWhole;
    private javax.swing.JComboBox<String> Time;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancelReservation;
    private javax.swing.JButton confirmChanges;
    private javax.swing.JButton edit;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField firstName1;
    private javax.swing.JTextField firstName2;
    private javax.swing.JTextField firstName3;
    private javax.swing.JTextField firstName4;
    private javax.swing.JButton homeButt;
    private javax.swing.JButton homeButt2;
    private javax.swing.JButton homeButt3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JComboBox<String> partySize;
    private javax.swing.JButton profileButt;
    private javax.swing.JButton profileButt2;
    private javax.swing.JButton profileButt3;
    private javax.swing.JButton reservationButt;
    private javax.swing.JTextField reservationFor;
    private javax.swing.JToggleButton saveInfo;
    private javax.swing.JToggleButton signOut;
    private javax.swing.JTextField status;
    private javax.swing.JButton statusButt;
    private javax.swing.JButton statusButt2;
    private javax.swing.JButton statusButt3;
    private javax.swing.JPanel tab;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JTabbedPane userTab;
    // End of variables declaration//GEN-END:variables
}



