/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalresprog;

import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Chupapi
 */
public class LOGIN extends connect {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        //connect();
       USER.setBackground (new java.awt.Color(0,0,0,1));
       PASS.setBackground (new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Type = new javax.swing.JComboBox<>();
        USER = new javax.swing.JTextField();
        PASS = new javax.swing.JPasswordField();
        clear = new javax.swing.JButton();
        bgc = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 675));
        getContentPane().setLayout(null);

        Type.setBackground(new java.awt.Color(255, 153, 153));
        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "USER" }));
        getContentPane().add(Type);
        Type.setBounds(300, 220, 80, 30);

        USER.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        USER.setOpaque(false);
        USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERActionPerformed(evt);
            }
        });
        getContentPane().add(USER);
        USER.setBounds(400, 260, 410, 40);

        PASS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSActionPerformed(evt);
            }
        });
        getContentPane().add(PASS);
        PASS.setBounds(400, 370, 410, 40);

        clear.setBackground(new java.awt.Color(153, 0, 0));
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(560, 530, 80, 30);

        bgc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcImage/Log-In (1).png"))); // NOI18N
        getContentPane().add(bgc);
        bgc.setBounds(0, 0, 1200, 675);

        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn);
        loginbtn.setBounds(535, 450, 130, 70);

        register.setText("jButton1");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(980, 110, 150, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        //USERNAME = USER.getText();
        String username = USER.getText();
        String password = new String(PASS.getPassword());

        Connect connect = new Connect();
        Connection connection = connect.getConnection();
        
        try {
             String sql = "SELECT * FROM ACCOUNT WHERE username = ? AND password = ?";
             PreparedStatement statement = connection.prepareStatement(sql);
             statement.setString(1, username);
             statement.setString(2, password);
             ResultSet resultSet = statement.executeQuery();
             if (resultSet.next()) {
                 JOptionPane.showMessageDialog(this, "Login successful!");
             } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password!");
             }
    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        connect.closeConnection();
        }
        
    }//GEN-LAST:event_loginbtnActionPerformed

    private void USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERActionPerformed

    private void PASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        LOGIN.this.dispose();
        RegistrationFrame registrationFrame = new RegistrationFrame(); // Create an instance of RegistrationFrame
        registrationFrame.setVisible(true); // Make the RegistrationFrame visible
        
    }//GEN-LAST:event_registerActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        USER.setText(""); // Clear the user field
        PASS.setText(""); // Clear the password field
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

   

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PASS;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JTextField USER;
    private javax.swing.JLabel bgc;
    private javax.swing.JButton clear;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables

}