/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalresprog;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author arell
 */
public class ReservationFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReservationFrame
     */
    public ReservationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsofReservation = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Time = new javax.swing.JComboBox<>();
        partySize = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        bcg1 = new javax.swing.JLabel();
        contactInfo = new javax.swing.JButton();
        next = new javax.swing.JToggleButton();
        btn_back1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_complete = new javax.swing.JButton();
        bcg = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        reservationTab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Time.setBackground(new java.awt.Color(153, 0, 0));
        Time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(choose)", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM", "10:00 PM" }));
        Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeActionPerformed(evt);
            }
        });
        jPanel2.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 160, 50));

        partySize.setBackground(new java.awt.Color(153, 0, 0));
        partySize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(choose)", "1 guest", "2 guests", "3 guests", "4 guests", "5 guests", "6 guests", "7 guests", "8 guests", "9 guests", "10 guests", "11 guests", "12 guests", "13 guest", "14 guests", "15 guests", "16 guests", "17 guests", "18 guests", "19 guests", "20 guests", " " }));
        partySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partySizeActionPerformed(evt);
            }
        });
        jPanel2.add(partySize, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 160, 50));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Request a reservation");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Fill the forms and we'll try to provide you a wonderful experience.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 170, 50));

        bcg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcImage/Reservation Information1.png"))); // NOI18N
        jPanel2.add(bcg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 675));

        contactInfo.setText("jButton1");
        contactInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactInfoActionPerformed(evt);
            }
        });
        jPanel2.add(contactInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 190, 100));

        next.setText("jToggleButton1");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, 140, 60));

        btn_back1.setBackground(new java.awt.Color(153, 0, 0));
        btn_back1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_back1.setForeground(new java.awt.Color(255, 255, 255));
        btn_back1.setText("Cancel");
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 150, 60));

        tabsofReservation.addTab("tab2", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setText(" I AGREE ON TERMS AND CONDITIONS");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 230, 60));

        btn_complete.setBackground(new java.awt.Color(255, 255, 255));
        btn_complete.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btn_complete.setText("Complete");
        btn_complete.setEnabled(false);
        btn_complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_completeActionPerformed(evt);
            }
        });
        btn_complete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_completeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn_completeKeyTyped(evt);
            }
        });
        jPanel1.add(btn_complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, 150, 60));

        bcg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/srcImage/Terms & Condition (Concept).png"))); // NOI18N
        jPanel1.add(bcg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 675));

        btn_back.setBackground(new java.awt.Color(153, 0, 0));
        btn_back.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Cancel");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 140, 60));

        reservationTab.setText("jButton1");
        reservationTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationTabActionPerformed(evt);
            }
        });
        jPanel1.add(reservationTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 140, 60));

        tabsofReservation.addTab("tab1", jPanel1);

        getContentPane().add(tabsofReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -25, 1240, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        ReservationFrame.this.dispose();
        HomeFrame homeFrame = new HomeFrame();
        homeFrame.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_completeActionPerformed
        JOptionPane.showMessageDialog(this, "Transaction complete, wait for confirmation.", "Transaction Complete", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        HomeFrame homeFrame = new HomeFrame(); // Create an instance of HomeFrame
        homeFrame.setVisible(true); // Make the HomeFrame visible
    }//GEN-LAST:event_btn_completeActionPerformed

    
        

    private void btn_completeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_completeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_completeKeyPressed

    private void btn_completeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_completeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_completeKeyTyped

    private void contactInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactInfoActionPerformed
        // TODO add your handling code here:
        tabsofReservation.setSelectedIndex(1);
    }//GEN-LAST:event_contactInfoActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        tabsofReservation.setSelectedIndex(1);
    }//GEN-LAST:event_nextActionPerformed

    private void TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TimeActionPerformed

    private void partySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partySizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partySizeActionPerformed

    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        // TODO add your handling code here:
        ReservationFrame.this.dispose();
        HomeFrame homeFrame = new HomeFrame();
        homeFrame.setVisible(true);
        
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void reservationTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationTabActionPerformed
        // TODO add your handling code here:
        tabsofReservation.setSelectedIndex(0);

    }//GEN-LAST:event_reservationTabActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        boolean isChecked = jCheckBox1.isSelected();
    
        // Enable the "button_complete" if the checkbox is selected
        btn_complete.setEnabled(isChecked);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Time;
    private javax.swing.JLabel bcg;
    private javax.swing.JLabel bcg1;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_complete;
    private javax.swing.JButton contactInfo;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton next;
    private javax.swing.JComboBox<String> partySize;
    private javax.swing.JButton reservationTab;
    private javax.swing.JTabbedPane tabsofReservation;
    // End of variables declaration//GEN-END:variables
}
